server.port=8081
message=Chao mung den voi Patient Service tu Config Server 
spring.application.name=patient-service
spring.datasource.url=jdbc:postgresql://localhost:5432/patient_db
spring.datasource.username=postgres
spring.datasource.password=123456