message: "Chao mung den voi Patient Service tu Config Server"

spring:
  application:
    name: patient-service
  datasource:
    url: jdbc:postgresql://localhost:5432/patient_db
    username: postgres
    password: 123456
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

app:
  welcome: "Chao mung toi BV RikkeiAcademy"